export const API_ENDPOINTS = {
  LOGIN: "auth/login",
  ADMIN_DASHBOARD:"admin",
  GET_PRODUCTS:"admin/products",
  ADD_PRODUCT: "admin/product",
  UPDATE_PRODUCT: "admin/product/{id}",
  DELETE_PRODUCT: "admin/product/{id}",
  GET_PRODUCT_BY_ID: "admin/product/{id}",
  CHANGE_PRODUCT_STATUS: "admin/change-product-status/{id}",
  ADD_HYMN:"admin/hymn",
  UPDATE_HYMN:"admin/hymn/{id}",
  DELETE_HYMN:"admin/hymn/{id}",
  GET_HYMN_BY_ID:"admin/hymn/{id}",
  GET_HYMNS_BY_PRODUCT:"admin/hymns/{productId}",
  LANGUAGES:"admin/languages",
  CREATE_LANGUAGES:"admin/languages",
  GET_LANGUAGE_CODE:"admin/languages/codes",
  UPDATE_LANGUAGE:"admin/languages/{id}",
  DELETE_LANGUAGE:"admin/languages/{id}",
  GET_LANGUAGE_BY_ID:"admin/languages/{id}"
};